config/routes.rb
Rails.application.routes.draw do

  # 以下deviseのルートパス
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'user/users#top'


  # 以下adminのルートパス
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get 'leave' => 'users#leave'
      end
    end
  end

  namespace :admin do
    resources :shops, only: [:new, :index, :show, :edit, :update, :destroy] do
      collection do
        get 'delete' => 'shops#delete'
      end
      resources :shop_images, only: [:destroy]
    end
  end

  # ジャンル直下にshopを置きたくないので、shopとは別に設定しています
  namespace :admin do
    resources :genres, only: [:new, :index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :newses
  end



  # 以下userのルートパス
  scope module: :user do
    resources :users, only: %i(show edit update destroy) do
      collection do
        get 'top'
        get 'about'
        get 'quit'
        patch 'out'
        delete 'registration'
      end
    end
  end

  scope module: :user do
    resources :shops, only: [:new, :create, :index, :show] do
      # resourcesだとurlにshop_idを介してしまい、
      # 全体のランキングページを表示できないので、collection doで別にしています
      collection do
        get 'reviews' => 'reviews#index'
      end
      resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]

      # resourcesだとurlにshop_idを介してしまい、
      # 特定のユーザーがブックマークしたもののみを表示できないので、collection doで別にしています
      collection do
        get 'bookmark' => 'bookmarks#show'
      end

      resource :bookmarks, only: %i(create destroy)
    end
  end

  scope module: :user do
    resources :searches, only: [:index] do
      collection do
        get 'placegenre' => 'searches#placegenre'
      end
    end
  end

  scope module: :user do
    resources :contacts, only: %i(new create)
  end

  scope module: :user do
    resources :newses, only: %i(index show)
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  # :addressを登録した際にgeocoderが緯度、経度のカラムにも自動的に値を入れてくれるようになる。
  # この記述がないとaddressを登録してもlatitude(緯度),longitude(経度)が登録されなくなってしまう(nillになる)ので注意。
  geocoded_by :address
  after_validation :geocode

  belongs_to :genre
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # 写真の複数投稿
  has_many :shop_images, dependent: :destroy
  accepts_attachments_for :shop_images, attachment: :shop_image

  # 空欄ではないか
  validates :name, :introduction, :address, :genre_id, :phone_number,
            :station, :home_page, :holiday, presence: true

  # 一意性があるか
  validates :name, :address, :phone_number, uniqueness: true
  # 長くなりすぎないようにするために最大200文字に指定
  validates :introduction, length: { maximum: 200 }
  # 日本一長い駅名が22文字のため
  validates :station, length: { maximum: 22 }
  # 携帯電話の番号が11文字のため、最大11桁に指定
  validates :phone_number, length: { maximum: 11 }
  # 数字のみ入力可能
  validates :phone_number, numericality: { only_integer: true }

  # 投稿したカフェデータをuser側では「掲載許可」のみを表示させたいので記載
  enum is_active: { "申請中": 0, "掲載許可": 1, "掲載禁止": 2 }

  # user側のshop/show.htmlにて使用
  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  # どのselectにデータが入っているかを確認する
  # self, クラスメソッド化することで、searchコントローラーで使用することができる
  def self.distinguish_select(params)
    # 「真(true)」となった場合に実行したい処理 if 条件式
    select = params[:select1] if (params[:select1]).present?
    select = params[:select2] if (params[:select2]).present?
    select = params[:select3] if (params[:select3]).present?
    select = params[:select4] if (params[:select4]).present?
    select = params[:select5] if (params[:select5]).present?
    select = params[:select6] if (params[:select6]).present?
    select = params[:select7] if (params[:select7]).present?
    select = params[:select8] if (params[:select8]).present?
    select = params[:select9] if (params[:select9]).present?
    select = params[:select10] if (params[:select10]).present?
    select = params[:select11] if (params[:select11]).present?
    select = params[:select12] if (params[:select12]).present?
    select = params[:select13] if (params[:select13]).present?
    select = params[:select14] if (params[:select14]).present?
    select = params[:select15] if (params[:select15]).present?
    select = params[:select16] if (params[:select16]).present?
    select
  end

  # ↓この書き方で検索することも可能らしい
  # wheres = []
  # params[:addresses].each do |address|
  #   wheres << ["address LIKE ?", "%#{address}%"]
  # end
  # Shop.wehre(wheres)


  # コントローラーで受け取った値をここで検索する
  def self.search(select, genre)
    # 大阪府
    # 大阪市
    if select == 'o-kita'
      Shop.where(['address LIKE ?', '%大阪市北区%'])
    elsif select == 'toshima'
      Shop.where(['address LIKE ?', '%豊島区%'])
    elsif select == 'fukushima'
      Shop.where(['address LIKE ?', '%福島区%'])
    elsif select == 'konohana'
      Shop.where(['address LIKE ?', '%此花区%'])
    elsif select == 'o-tyuuou'
      Shop.where(['address LIKE ?', '%大阪市中央区%'])
    elsif select == 'o-nisi'
      Shop.where(['address LIKE ?', '%大阪市西区%'])
    elsif select == 'minato'
      Shop.where(['address LIKE ?', '%港区%'])
    elsif select == 'taishou'
      Shop.where(['address LIKE ?', '%大正区%'])
    elsif select == 'tennouji'
      Shop.where(['address LIKE ?', '%天王寺区%'])
    elsif select == 'naniwa'
      Shop.where(['address LIKE ?', '%浪速区%'])
    elsif select == 'nishiyodogawa'
      Shop.where(['address LIKE ?', '%西淀川区%'])
    elsif select == 'yodogawa'
      Shop.where(['address LIKE ?', '%淀川区%'])
    elsif select == 'higashiyodogawa'
      Shop.where(['address LIKE ?', '%東淀川区%'])
    elsif select == 'higasinari'
      Shop.where(['address LIKE ?', '%東成区%'])
    elsif select == 'ikuno'
      Shop.where(['address LIKE ?', '%生野区%'])
    elsif select == 'asahi'
      Shop.where(['address LIKE ?', '%旭区%'])
    elsif select == 'joutou'
      Shop.where(['address LIKE ?', '%城東区%'])
    elsif select == 'turumi'
      Shop.where(['address LIKE ?', '%鶴見区%'])
    elsif select == 'abeno'
      Shop.where(['address LIKE ?', '%阿倍野区%'])
    elsif select == 'suminoe'
      Shop.where(['address LIKE ?', '%住之江区%'])
    elsif select == 'sumiyoshi'
      Shop.where(['address LIKE ?', '%住吉区%'])
    elsif select == 'higashisuminoe'
      Shop.where(['address LIKE ?', '%東住之江区%'])
    elsif select == 'higashisumiyoshi'
      Shop.where(['address LIKE ?', '%東住吉区%'])
    elsif select == 'hirano'
      Shop.where(['address LIKE ?', '%平野区%'])
    elsif select == 'nishinari'
      Shop.where(['address LIKE ?', '%西成区%'])
    # 堺市
    elsif select == 'sakai'
      Shop.where(['address LIKE ?', '%堺区%'])
    elsif select == 'o-s-naka'
      Shop.where(['address LIKE ?', '%堺市中区%'])
    elsif select == 'o-s-higasi'
      Shop.where(['address LIKE ?', '%堺市東区%'])
    elsif select == 'o-s-nishi'
      Shop.where(['address LIKE ?', '%堺市西区%'])
    elsif select == 'o-s-minami'
      Shop.where(['address LIKE ?', '%堺市南区%'])
    elsif select == 'o-s-kita'
      Shop.where(['address LIKE ?', '%堺市北区%'])
    elsif select == 'mihara'
      Shop.where(['address LIKE ?', '%美原区%'])
    # 豊能地域
    elsif select == 'nose'
      Shop.where(['address LIKE ?', '%能勢町%'])
    elsif select == 'toyono'
      Shop.where(['address LIKE ?', '%豊能町%'])
    elsif select == 'ikeda'
      Shop.where(['address LIKE ?', '%池田市%'])
    elsif select == 'minou'
      Shop.where(['address LIKE ?', '%箕面市%'])
    elsif select == 'toyonaka'
      Shop.where(['address LIKE ?', '%豊中市%'])
    # 三島地域
    elsif select == 'ibaraki'
      Shop.where(['address LIKE ?', '%茨木市%'])
    elsif select == 'takatsuki'
      Shop.where(['address LIKE ?', '%高槻市%'])
    elsif select == 'shimamoto'
      Shop.where(['address LIKE ?', '%島本町%'])
    elsif select == 'suita'
      Shop.where(['address LIKE ?', '%吹田市%'])
    elsif select == 'settu'
      Shop.where(['address LIKE ?', '%摂津市%'])
    # 北河内地域
    elsif select == 'hirakata'
      Shop.where(['address LIKE ?', '%枚方市%'])
    elsif select == 'katano'
      Shop.where(['address LIKE ?', '%交野市%'])
    elsif select == 'neyagawa'
      Shop.where(['address LIKE ?', '%寝屋川市%'])
    elsif select == 'moriguchi'
      Shop.where(['address LIKE ?', '%守口市%'])
    elsif select == 'kadoma'
      Shop.where(['address LIKE ?', '%門真市%'])
    elsif select == 'shijounawate'
      Shop.where(['address LIKE ?', '%四條畷市%'])
    elsif select == 'daitou'
      Shop.where(['address LIKE ?', '%大東市%'])
    # 中河内地域
    elsif select == 'higashiosaka'
      Shop.where(['address LIKE ?', '%東大阪市%'])
    elsif select == 'yao'
      Shop.where(['address LIKE ?', '%八尾市%'])
    elsif select == 'kashiwara'
      Shop.where(['address LIKE ?', '%柏原市%'])
    # 泉北地域
    elsif select == 'izumi'
      Shop.where(['address LIKE ?', '%和泉市%'])
    elsif select == 'takaishi'
      Shop.where(['address LIKE ?', '%高石市%'])
    elsif select == 'izumiotsu'
      Shop.where(['address LIKE ?', '%泉大津市%'])
    elsif select == 'tadooka'
      Shop.where(['address LIKE ?', '%忠岡市%'])
    # 泉南地域
    elsif select == 'kishiwada'
      Shop.where(['address LIKE ?', '%岸和田市%'])
    elsif select == 'kaizuka'
      Shop.where(['address LIKE ?', '%貝塚市%'])
    elsif select == 'kumatori'
      Shop.where(['address LIKE ?', '%熊取町%'])
    elsif select == 'izumisano'
      Shop.where(['address LIKE ?', '%泉佐野市%'])
    elsif select == 'tajiri'
      Shop.where(['address LIKE ?', '%田尻町%'])
    elsif select == 'sennan'
      Shop.where(['address LIKE ?', '%泉南市%'])
    elsif select == 'hannan'
      Shop.where(['address LIKE ?', '%阪南市%'])
    elsif select == 'misaki'
      Shop.where(['address LIKE ?', '%岬町%'])
    # 南河内地域
    elsif select == 'matsubara'
      Shop.where(['address LIKE ?', '%松原市%'])
    elsif select == 'habikino'
      Shop.where(['address LIKE ?', '%羽曳野市%'])
    elsif select == 'fujidera'
      Shop.where(['address LIKE ?', '%藤井寺市%'])
    elsif select == 'taishi'
      Shop.where(['address LIKE ?', '%太子町%'])
    elsif select == 'kanan'
      Shop.where(['address LIKE ?', '%河南町%'])
    elsif select == 'tihayaakasaka'
      Shop.where(['address LIKE ?', '%千早赤阪村%'])
    elsif select == 'tondabayashi'
      Shop.where(['address LIKE ?', '%富田林市%'])
    elsif select == 'sayama'
      Shop.where(['address LIKE ?', '%狭山市%'])
    elsif select == 'kawachinagano'
      Shop.where(['address LIKE ?', '%河内長野市%'])

    # 京都府
    # 京都市
    elsif select == 'k-kita'
      Shop.where(['address LIKE ?', '%京都市北区%'])
    elsif select == 'kamigyou'
      Shop.where(['address LIKE ?', '%上京区%'])
    elsif select == 'sakyou'
      Shop.where(['address LIKE ?', '%左京区%'])
    elsif select == 'nakagyou'
      Shop.where(['address LIKE ?', '%中京区%'])
    elsif select == 'higashiyama'
      Shop.where(['address LIKE ?', '%東山区%'])
    elsif select == 'simogyou'
      Shop.where(['address LIKE ?', '%下京区%'])
    elsif select == 'k-minami'
      Shop.where(['address LIKE ?', '%京都市南区%'])
    elsif select == 'ukyou'
      Shop.where(['address LIKE ?', '%右京区%'])
    elsif select == 'fushimi'
      Shop.where(['address LIKE ?', '%伏見区%'])
    elsif select == 'yamashina'
      Shop.where(['address LIKE ?', '%山科区%'])
    elsif select == 'nishikyou'
      Shop.where(['address LIKE ?', '%西京区%'])
    # 乙訓地域
    elsif select == 'mukou'
      Shop.where(['address LIKE ?', '%向日市%'])
    elsif select == 'nagaokakyou'
      Shop.where(['address LIKE ?', '%長岡京市%'])
    elsif select == 'otokumi'
      Shop.where(['address LIKE ?', '%乙訓群%'])
    elsif select == 'oyamasaki'
      Shop.where(['address LIKE ?', '%大山崎町%'])
    # 山城中部地域
    elsif select == 'uji'
      Shop.where(['address LIKE ?', '%宇治市%'])
    elsif select == 'jouyou'
      Shop.where(['address LIKE ?', '%城陽市%'])
    elsif select == 'hachiman'
      Shop.where(['address LIKE ?', '%八幡市%'])
    elsif select == 'kyoutanabe'
      Shop.where(['address LIKE ?', '%京田辺市%'])
    elsif select == 'kuse'
      Shop.where(['address LIKE ?', '%久世郡%'])
    elsif select == 'kumiyama'
      Shop.where(['address LIKE ?', '%久御山町%'])
    elsif select == 'tuduki'

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!

  def delete
    @shops = Shop.page(params[:page]).reverse_order
  end

  def new
    @shops = Shop.page(params[:page]).reverse_order
    @genres = Genre.all
  end

  def index
    @shops = Shop.page(params[:page]).reverse_order
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def edit
    @shop = Shop.find(params[:id])
    @genres = Genre.all
  end

  def update
    @shop = Shop.find(params[:id])
    @genres = Genre.all
    if @shop.update(shop_params)
      flash[:success] = 'カフェのデータを更新しました'
      redirect_to new_admin_shop_path
    else
      render :edit
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    flash[:success] = 'カフェのデータを削除しました'
    redirect_to admin_shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :introduction, :shop_image, :address, :genre_id, :start_business_hours,
                                 :finish_business_hours, :station, :phone_number, :home_page, :holiday, :longitude, :latitude, :is_active, shop_images_shop_images: [])
  end
end

app/controllers/user/shops_controller.rb
class User::ShopsController < ApplicationController
  before_action :authenticate_user!

  def new
    @shop = Shop.new
    @shop.shop_images.new
    @genres = Genre.all
  end

  def create
    @shop = Shop.new(shop_params)

    # time_selectを使うと年月日を登録しないといけないが、このアプリでは年の登録をしていないため、自動的に西暦1年で登録されてしまい、LMTになってしまう。
    # LMTで登録した時間を上書きして表示させるため、下記を記載, 2000は西暦を上書きしている
    s_time = Time.zone.local(2000, shop_params["start_business_hours(2i)"], shop_params["start_business_hours(3i)"],
                             shop_params["start_business_hours(4i)"], shop_params["start_business_hours(5i)"])
    f_time = Time.zone.local(2000, shop_params["finish_business_hours(2i)"], shop_params["finish_business_hours(3i)"],
                             shop_params["finish_business_hours(4i)"], shop_params["finish_business_hours(5i)"])

    @shop.start_business_hours = s_time
    @shop.finish_business_hours = f_time

    @genres = Genre.all
    if @shop.save
      flash[:success] = "リクエスト頂きありがとうございます！"
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def index
    @shops = Shop.page(params[:page]).reverse_order
  end

  def show
    @shop = Shop.find(params[:id])
    @user = current_user
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :introduction, :address, :genre_id, :start_business_hours,
                                 :finish_business_hours, :station, :phone_number, :home_page, :holiday, :longitude, :latitude, shop_images_shop_images: [])
  end
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/user/shops_helper.rb
module User::ShopsHelper
end

app/views/admin/shops/delete.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <table border="1">
        <thead>
          <tr>
            <h3 class="text-center">掲載禁止カフェ一覧</h3>
          </tr>
<br>
          <tr>
            <i class="fa fa-history"></i><%= link_to "戻る", admin_shops_path %>
          </tr>
          <tr>
            <td>ID</td>
            <td>カフェ名</td>
          </tr>
        </thead>
        <% @shops.each do |shop| %>
          <% if shop.is_active == "掲載禁止" %>
          <tbody>
            <tr>
              <td><%= shop.id %></td>
              <td>
                <%= link_to admin_shop_path(shop) do %>
                  <%= shop.name %>
                <% end %>
              </td>
            </tr>
          </tbody>
          <% end %>
        <% end %>
        <tr>
  	  		<%= paginate @shops %>
  			</tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/shops/edit.html.erb
<div class="container">
  <div class="row">
    <div class="card col-sm-6 mx-auto mt-5">
      <div class="card-body">
        <tr>
          <h5 class="text-center" style="color: limegreen"><%= flash[:success] %></h5>
        </tr>

        <tr>
          <i class="fa fa-history"></i><%= link_to "戻る", new_admin_shop_path %>
        </tr>
<br>
        <tr>
          <%= render 'layouts/error_messages', messages: @shop %>
        </tr>
        <h3 class="mt-1 mb-3">登録情報編集</h3>
        <%= form_with model: @shop, url: admin_shop_path(@shop), local:true do |f| %>

        <div class="form-group">
          <%= f.label :shop_image, "写真(追加ではなく上書きします)", :class => "form-label" %>
          <%= f.attachment_field :shop_images_shop_images, multiple: true %>
        </div>

        <div class="form-group">
          <% if @shop.shop_images.present? %>
            <% @shop.shop_images.each do |shop_image| %>
              <%= attachment_image_tag shop_image, :shop_image, size: "200x200" %>
              <%= link_to "削除する", admin_shop_shop_image_path(shop_image.shop.id, shop_image.id), method: :delete %><br>
            <% end %>
          <% else %>
            <%= image_tag "no_image.jpg", size: "200x200" %>
          <% end %>
        </div>




        <div class="form-group">
          <%= f.label :name, "店名", :class => "form-label" %>&nbsp;<span class="label label-danger">必須</span>
          <%= f.text_field :name, autocomplete: "name", :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :introduction, "お店紹介文", :class => "form-label" %>&nbsp;<span class="label label-danger">必須</span>
          <%= f.text_field :introduction, autocomplete: "introduction", :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :address, "住所", :class => "form-label" %>&nbsp;<span class="label label-danger">必須</span>
          <%= f.text_field :address, :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :genre, "ジャンル", :class => "form-label" %>
          <%= f.collection_select(:genre, @genres, :id, :name, autocomplete: "genre_id", :class => "form-control") %>
        </div>

        <div class="form-group">
          <%= f.label :start_business_hours, "営業時間", :class => "form-label" %>
          <%= f.time_select :start_business_hours, autocomplete: "start_business_hours", :class => "form-control" %>~<%= f.time_select :finish_business_hours, autocomplete: "finish_business_hours", :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :station, "最寄駅", :class => "form-label" %>&nbsp;<span class="label label-danger">必須</span>
          <%= f.text_field :station, autocomplete: "station", :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :phone_number, "電話番号(ハイフンなし)", :class => "form-label" %>&nbsp;<span class="label label-danger">必須</span>
          <%= f.text_field :phone_number, autocomplete: "phone_number", :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :home_page, "ホームページ", :class => "form-label" %>&nbsp;<span class="label label-danger">必須</span>
          <%= f.text_field :home_page, autocomplete: "home_page", :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :holiday, "休日", :class => "form-label" %>&nbsp;<span class="label label-danger">必須</span>
          <%= f.text_field :holiday, autocomplete: "holiday", :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.select :is_active, [["申請中", "申請中"], ["掲載許可", "掲載許可"], ["掲載禁止", "掲載禁止"]] %>
        </div>

        <div class="actions">
          <%= f.submit "更新する", :class => "btn btn-primary btn-block" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/shops/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <table border="1">
        <thead>
          <tr>
            <h5 class="text-center" style="color: limegreen"><%= flash[:success] %></h5>
          </tr>
          <tr>
            <h3 class="text-center">登録済みカフェ一覧</h3>
          </tr>
<br>
          <tr>
            <%= link_to delete_admin_shops_path do %>
              掲載禁止カフェ一覧へ
            <% end %>
          </tr>
          <tr>
            <td>ID</td>
            <td>カフェ名</td>
          </tr>
        </thead>
        <% @shops.each do |shop| %>
          <% if shop.is_active == "掲載許可" %>
          <tbody>
            <tr>
              <td><%= shop.id %></td>
              <td>
                <%= link_to admin_shop_path(shop) do %>
                  <%= shop.name %>
                <% end %>
              </td>
            </tr>
          </tbody>
          <% end %>
        <% end %>
        <tr>
  	  		<%= paginate @shops %>
  			</tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/shops/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table border="1">
        <thead>
          <tr>
  	        <h5 class="text-center" style="color: limegreen"><%= flash[:success] %></h5>
  	      </tr>
  	      <tr>
            <h3 class="text-center">登録申請カフェ一覧</h3>
            <p class="text-center">申請中のカフェがあれば表示されます</p>
          </tr>
        </thead>

<br>
        <% @shops.each do |shop| %>
          <% if shop.is_active == "申請中"  %>
          <tbody>
            <tr>
              <td><%= shop.id %></td>
              <td>
                <%= link_to edit_admin_shop_path(shop) do %>
                  <%= shop.name %>
                <% end %>
              </td>
            </tr>
          </tbody>
          <% end %>
        <% end %>
        <tr>
  	  		<%= paginate @shops %>
  			</tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/shops/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table border="1">
        <thead>
          <tr>
  	        <h5 class="text-center" style="color: limegreen"><%= flash[:success] %></h5>
  	      </tr>
          <h3 class="text-center"><%= @shop.name %>の詳細ページ</h3>
        </thead>
        <tbody>
          <tr style="text-align: center;">
            <h5 class="text-left">
              <i class="fa fa-history"></i><%= link_to "戻る", admin_shops_path %>
            </h5>
          </tr>
          <tr>
            <th>店名</th>
            <td><%= @shop.name %></td>
          </tr>
          <tr>
            <th>お店の紹介文</th>
            <td><%= simple_format(@shop.introduction) %></td>
          </tr>
          <tr>
            <th>お店の写真</th>
            <td>
            <% if @shop.shop_images.present? %>
              <% @shop.shop_images.each do |shop_image| %>
                <%= attachment_image_tag shop_image, :shop_image, size: "200x200" %>
              <% end %>
            <% else %>
              <%= image_tag "no_image.jpg", size: "200x200" %>
            <% end %>
            </td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= @shop.address %></td>
          </tr>
          <tr>
            <th>ジャンル</th>
            <td><%= @shop.genre.name %></td>
          </tr>
          <tr>
            <th>営業時間</th>
             <td><%= @shop.start_business_hours.strftime('%H:%M') %>〜<%= @shop.finish_business_hours.strftime('%H:%M') %></td>
          </tr>
          <tr>
            <th>最寄駅</th>
            <td><%= @shop.station %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= @shop.phone_number %></td>
          </tr>
          <tr>
            <th>ホームページ</th>
            <td>
            <% if @shop.home_page == "なし" %>
              なし
            <% else %>
              <%= link_to @shop.home_page do %>
                <%= @shop.name %>のホームページリンク
              <% end %>
            <% end %>
            </td>
          </tr>
          <tr>
            <th>休日</th>
             <td><%= @shop.holiday %></td>
          </tr>
          <tr>
            <th></th>
            <td>
              <%= link_to "編集する", edit_admin_shop_path(@shop), :class => "btn btn-primary"  %>&nbsp;&nbsp;&nbsp;
              <%= link_to "削除する", admin_shop_path(@shop), method: :delete, :class => "btn btn-primary"  %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>