config/routes.rb
Rails.application.routes.draw do

  # 以下deviseのルートパス
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: 'user/users#top'


  # 以下adminのルートパス
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update] do
      collection do
        get 'leave' => 'users#leave'
      end
    end
  end

  namespace :admin do
    resources :shops, only: [:new, :index, :show, :edit, :update, :destroy] do
      collection do
        get 'delete' => 'shops#delete'
      end
      resources :shop_images, only: [:destroy]
    end
  end

  # ジャンル直下にshopを置きたくないので、shopとは別に設定しています
  namespace :admin do
    resources :genres, only: [:new, :index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :newses
  end



  # 以下userのルートパス
  scope module: :user do
    resources :users, only: %i(show edit update destroy) do
      collection do
        get 'top'
        get 'about'
        get 'quit'
        patch 'out'
        delete 'registration'
      end
    end
  end

  scope module: :user do
    resources :shops, only: [:new, :create, :index, :show] do
      # resourcesだとurlにshop_idを介してしまい、
      # 全体のランキングページを表示できないので、collection doで別にしています
      collection do
        get 'reviews' => 'reviews#index'
      end
      resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]

      # resourcesだとurlにshop_idを介してしまい、
      # 特定のユーザーがブックマークしたもののみを表示できないので、collection doで別にしています
      collection do
        get 'bookmark' => 'bookmarks#show'
      end

      resource :bookmarks, only: %i(create destroy)
    end
  end

  scope module: :user do
    resources :searches, only: [:index] do
      collection do
        get 'placegenre' => 'searches#placegenre'
      end
    end
  end

  scope module: :user do
    resources :contacts, only: %i(new create)
  end

  scope module: :user do
    resources :newses, only: %i(index show)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 簡単ログイン機能実装のため記載
  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: "ゲストユーザー", gender: "男性", introduction: "ゲストユーザーです") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  enum gender: { "男性": 1, "女性": 2 }

  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, :gender, :email, presence: true
  validates :name, uniqueness: true
  validates :introduction, length: { maximum: 100 }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def leave
    @users = User.page(params[:page]).reverse_order
  end

  def index
    @users = User.page(params[:page]).reverse_order
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を更新しました'
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :introduction, :gender, :phone_number, :address, :user_status)
  end
end

app/controllers/user/bookmarks_controller.rb
class User::BookmarksController < ApplicationController
  before_action :authenticate_user!

  def show
    @bookmarks = Bookmark.where(user_id: current_user.id).page(params[:page]).reverse_order
  end

  def create
    @user = current_user
    @shop = Shop.find(params[:shop_id])
    bookmark = Bookmark.new(user_id: current_user.id, shop_id: @shop.id)
    bookmark.save
    flash[:success] = 'ブックマークしました'
  end

  def destroy
    @user = current_user
    @shop = Shop.find(params[:shop_id])
    bookmark = @shop.bookmarks.find_by(user_id: current_user.id)
    bookmark.destroy
    flash[:success] = 'ブックマークを外しました'
  end
end

app/controllers/user/contacts_controller.rb
class User::ContactsController < ApplicationController
  before_action :authenticate_user!

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      # contact_mailer.rbのメソッド(contact_mail(contact))を使用
      ContactMailer.contact_mail(@contact).deliver_later
      flash[:success] = 'お問い合わせ頂きありがとうございます!'
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :message, :email, :title)
  end
end

app/controllers/user/newses_controller.rb
class User::NewsesController < ApplicationController
  before_action :authenticate_user!

  def index
    @newses = News.page(params[:page]).reverse_order
  end

  def show
    @news = News.find(params[:id])
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @review = Review.new
    @shop = Shop.find(params[:shop_id])
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @review = Review.new(review_params)
    # アソシエーションしている際、データを紐づけるために「_id」にidを入れる
    @review.user_id = current_user.id
    @review.shop_id = @shop.id
    if @review.save
      redirect_to shop_path(@shop)
      flash[:success] = '評価頂きありがとうございます！'
    else
      render :new
    end
  end

  def index
    @shops = Shop.joins(:reviews).group(:shop_id).order('avg(rate) DESC')
    # @shops = Shop.page(params[:page])
    # @shops = Shop.all
    # sort_by, 配列を小さい順に並べる
    # 「@変数名 { |〇〇| }」でeach doを１行にした簡略文を作成できる
    # モデル.average(カラム名), カラムの平均化
    # .to_f.round(N), 小数点以下N桁の四捨五入
    # @average_shops = @shops.sort_by { |shop| shop.reviews.average(:rate).to_f.round(1) }.reverse
    # @shops = @average_shops.page(params[:page])
    @average_shops = @shops
    @shops = @shops.page(params[:page])
  end

  def show
    @review = Review.find(params[:shop_id])
  end

  def edit
    @review = Review.find(params[:shop_id])
    @shop = Shop.find(params[:id])
  end

  def update
    shop = Shop.find(params[:shop_id])
    review = Review.find(params[:id])
    review.update(review_params)
    redirect_to shop_path(shop)
  end

  def destroy
    shop = Shop.find(params[:shop_id])
    review = Review.find(params[:id])
    review.destroy
    redirect_to shop_path(shop)
  end

  def review_params
    params.require(:review).permit(:title, :body, :rate, :shop_id)
  end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def placegenre
    @genres = Genre.all
  end

  def index
    select = Shop.distinguish_select(params)
    @shops = if params[:search].present?
               Shop.where(['name LIKE ?', "%#{params[:search]}%"]).page(params[:page])
             else
               Shop.search(select, params[:genre]).page(params[:page])
             end
  end
end

app/controllers/user/shops_controller.rb
class User::ShopsController < ApplicationController
  before_action :authenticate_user!

  def new
    @shop = Shop.new
    @shop.shop_images.new
    @genres = Genre.all
  end

  def create
    @shop = Shop.new(shop_params)

    # time_selectを使うと年月日を登録しないといけないが、このアプリでは年の登録をしていないため、自動的に西暦1年で登録されてしまい、LMTになってしまう。
    # LMTで登録した時間を上書きして表示させるため、下記を記載, 2000は西暦を上書きしている
    s_time = Time.zone.local(2000, shop_params["start_business_hours(2i)"], shop_params["start_business_hours(3i)"],
                             shop_params["start_business_hours(4i)"], shop_params["start_business_hours(5i)"])
    f_time = Time.zone.local(2000, shop_params["finish_business_hours(2i)"], shop_params["finish_business_hours(3i)"],
                             shop_params["finish_business_hours(4i)"], shop_params["finish_business_hours(5i)"])

    @shop.start_business_hours = s_time
    @shop.finish_business_hours = f_time

    @genres = Genre.all
    if @shop.save
      flash[:success] = "リクエスト頂きありがとうございます！"
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def index
    @shops = Shop.page(params[:page]).reverse_order
  end

  def show
    @shop = Shop.find(params[:id])
    @user = current_user
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :introduction, :address, :genre_id, :start_business_hours,
                                 :finish_business_hours, :station, :phone_number, :home_page, :holiday, :longitude, :latitude, shop_images_shop_images: [])
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]

  def registration
    @user = current_user
    @user.destroy
    redirect_to new_user_registration_path
  end

  def top
    @users = User.all
    @user = @users.where(user_status: false).count

    @shops = Shop.all
    @shop = @shops.where(is_active: 1).count

    # 掲載許可したお店の評価数のみ表示するため、下記記述
    # 登録リクエスト中であったり、登録禁止にしたカフェはtopページの「登録カフェ数」にカウントされないようにしています
    @review = Review.joins(:shop).where("shops.is_active = 1").count
  end

  def about
  end

  def show
    @user = User.find(params[:id])
  end

  # 退会確認画面
  def quit
  end

  # 退会データを送信する
  def out
    @user = current_user
    # user_status(退会済みかを確認するカラム)をtrueに変更する(デフォルトはfalse)
    @user.update(user_status: true)
    # 退会するとログインできないようにするため、セッション情報を削除する
    reset_session
    flash[:success] = '退会が完了いたしました。ぜひまた遊びに来てください！'
    redirect_to root_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を更新しました'
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "ご利用いただきありがとうございました。ぜひまた遊びに来てください！"
    redirect_to root_path
  end



  private

  def user_params
    params.require(:user).permit(:email, :name, :introduction, :gender, :phone_number, :address)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # 退会機能時に追加↓
  before_action :reject_inactive_user, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # 退会機能時に追加↓
  def reject_inactive_user
    @user = User.find_by(name: params[:user][:name])
    redirect_to new_user_session_path if @user && @user.valid_password?(params[:user][:password]) && @user.user_status
  end

  def new_guest
    user = User.guest
    sign_in user
    flash[:success] = "ゲストユーザーとしてログインしました。"
    redirect_to user_path(user)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/bookmarks_helper.rb
module User::BookmarksHelper
end

app/helpers/user/contacts_helper.rb
module User::ContactsHelper
end

app/helpers/user/newses_helper.rb
module User::NewsesHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/user/users/about.html.erb
<div id="fh5co-page">
<header>
	<div class="container">
		<div class="fh5co-navbar-brand">
			<h1 class="text-center"><a class="fh5co-logo"><img src=<%= asset_path('logo.jpg') %>></a></h1>
		</div>
	</div>
</header>
<div id="fh5co-about-section">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center animate-box">
				<div class="about">
					<%= image_tag("icon.jpg") %>
				</div>
				<div class="desc">
					<h3>このアプリを作った人</h3>
					<p>たかき</p>

					<br><br>


					<h3>このアプリを作り始めた理由</h3>
					<br>
					<p>
						カフェ探しをする時にインスタ・Googleマップ・Web検索など色んなアプリを<br>経由して検索しているのですが、アプリを切り替えて検索していることが手間に
						<br>感じています。
						そこで、検索する手間を減らすため今までやっていたことを<br>
						一つのアプリで検索できるようにしたいと思い、このアプリを作成いたしました。
					</p>

					<br><br>

					<p>
						また、このアプリに登録されているカフェはユーザー皆様からリクエストを<br>
						いただいたカフェのみ表示しております。<br>
						おすすめのカフェがございましたら
						お気軽にリクエストいただけますと幸いです。
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="fh5co-photos-section">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3 text-center animate-box">
				<div class="heading-section">
					<h3>たかき's おすすめカフェを紹介</h3>
				</div>
			</div>
		</div>
		<div class="row text-center">
			<div class="col-md-4 animate-box">
				<div class="grid-photo" style="background-image: url(<%= asset_path('pic26.jpg') %>)">
					<div class="desc">
						<h3>カフェ英國屋</h3>
						<span>ヨーロッパの香り漂うカフェチェーン。<br>クラシックな椅子が並ぶゆったりとした空間での<br>モーニングはおすすめです。</span>
						<br><br><br>
						<span>大阪府大阪市中央区難波３丁目７−１０</span>
					</div>
				</div>
			</div>
			<div class="col-md-4 animate-box">
				<div class="grid-photo" style="background-image: url(<%= asset_path('pic20.jpg') %>)">
					<div class="desc">
						<h3>MISSLIM</h3>
						<span>京都、河原町丸太町を少し下ったところにある<br>紅茶専門店。<br>いろんな種類の紅茶を楽しみながら<br>のんびりできる素敵なお店です。</span>
						<br><br>
						<span>京都府京都市上京区伊勢屋町４００</span>
					</div>
				</div>
			</div>
			<div class="col-md-4 animate-box">
				<div class="grid-photo" style="background-image: url(<%= asset_path('pic19.jpg') %>)">
					<div class="desc">
						<h3>アラビカ</h3>
						<span>自家農園の珈琲豆を使い、店内で淹れた<br>オリジナルコーヒーが頂けちゃいます。<br>レジ前の壁面に様々な種類の珈琲豆が袋ごと<br>展示されていたことが印象的でした。</span>
						<br><br>
						<span>京都府京都市東山区星野町８７−５</span>
					</div>
				</div>
			</div>
			<div class="col-md-4 animate-box">
				<div class="grid-photo" style="background-image: url(<%= asset_path('pic22.jpg') %>)">
					<div class="desc">
						<h3>cafe太陽ノ塔</h3>
						<span>梅田にある隠れ家カフェ。<br>フードメニューが充実しており、<br>特にいちごケーキと焼きプリンは格別です。</span>
						<br><br><br>
						<span>大阪府大阪市北区中崎西２丁目４−３６</span>
					</div>
				</div>
			</div>
			<div class="col-md-4 animate-box">
				<div class="grid-photo" style="background-image: url(<%= asset_path('pic14.jpg') %>)">
					<div class="desc">
						<h3>茂庵</h3>
						<span>郊外の森の中に潜む緑に囲まれた古民家カフェ。<br>お店の窓からは京都市街を一望でき、<br>自然に囲まれた中でのひとときは格別です。</span>
						<br><br><br>
						<span>京都府京都市左京区吉田神楽岡町８</span>
					</div>
				</div>
			</div>
			<div class="col-md-4 animate-box">
				<div class="grid-photo" style="background-image: url(<%= asset_path('pic23.jpg') %>)">
					<div class="desc">
						<h3>Fluffy's Cafe</h3>
						<span>ねこ！ねこ！ねこ！<br>ねことねこがねこで溢れとる！<br>ねこ最高！！！</span>
						<br><br><br>
						<span>京都府京都市中京区新京極東入 裏寺町595−3</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<footer>
	<div id="footer">
		<div class="container">
			<div class="row copy-right">
				<div class="col-md-6 col-md-offset-3 text-center">
					<p>Copyright 2016 Free Html5 <a href="#">Focus</a>. All Rights Reserved. <br>Made with by <a href="http://freehtml5.co/" target="_blank">Freehtml5.co</a> / Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash </a></p>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="card col-sm-6 mx-auto mt-5">
      <div class="card-body">
        <div>
          <i class="fa fa-history"></i><%= link_to "戻る", user_path(current_user) %>
        </div>
<br>
        <%= render 'layouts/error_messages', messages: @user %>
        <h3 class="mt-1 mb-3">登録情報編集</h3>
        <%= form_with model: @user, url: user_path(@user), local:true do |f| %>

        <div class="form-group">
          <%= f.label :name, "ニックネーム", :class => "form-label" %>&nbsp;<span class="label label-danger">必須</span>
          <%= f.text_field :name, autocomplete: "name", :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :email, "メールアドレス", :class => "form-label" %>&nbsp;<span class="label label-danger">必須</span>
          <%= f.email_field :email, autocomplete: "email", :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :introduction, "自己紹介", :class => "form-label" %>
          <%= f.text_field :introduction, :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :gender, "男性" %>
          <%= f.radio_button :gender, "男性", autofocus: true %>
          <%= f.label :gender, "女性" %>
          <%= f.radio_button :gender, "女性", autofocus: true %>
        </div>

        <div class="actions text-center">
          <%= f.submit "編集を保存する", :class => "btn btn-primary" %>
          <%= link_to "退会する", quit_users_path, :class => "btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/users/quit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<table border="1" style="border-collapse: collapse">
				<thead>
					<th class="text-center">本当に退会しますか？</th>
				</thead>
				<br><br>
				<tbody>
					<tr>
						<td>
            退会すると会員情報登録や<br>
            これまで登録したブックマークが閲覧できなくなります。<br>
            <br>
            退会する場合は,「退会する」をクリックください。
						</td>
				  </tr>
				  <tr>
				  	<td>
				  		<%= link_to "退会しない",user_path(current_user), :class => "btn btn-primary" %>
				  		<%= link_to "退会する",out_users_path(current_user), method: :patch, :class => "btn btn-primary" %>
						</td>
				  </tr>
				 </tbody>
			</table>
		</div>
	</div>
</div>

app/views/user/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<table border="1">
				<thead>
				  <tr>
			      <h5 class="text-center" style="color: limegreen"><%= flash[:success] %></h5>
			    </tr>
				  <h3 class="text-center"><%= @user.name %>さんのユーザー情報</h3>
				</thead>
				<br><br>
				<tbody>
					<tr>
				    <th>氏名</th>
				    <td><%= @user.name %></td>
				  </tr>
				  <% if @user == current_user %>
				  <tr>
				    <th>メールアドレス</th>
				    <td><%= @user.email %></td>
				  </tr>
				  <% end %>
				  <tr>
				    <th>自己紹介</th>
				    <td><%= @user.introduction %></td>
				  </tr>
				</tbody>
			</table>
 <br>
 			<% if @user == current_user %>
			<table border="1">
			  <tr>
			  	<td>
		  		<% unless @user.name == "ゲストユーザー" %>
		  			<%= link_to "カフェ登録リクエスト", new_shop_path, :class => "btn btn-primary" %>
		  		<% else %>
		  			<%= link_to "カフェ登録リクエスト", registration_users_path, method: :delete, :class => "btn btn-primary" %>
		  		<% end %>
			  	</td>
					<td>
						<% unless @user.name == "ゲストユーザー" %>
							<% if @user == current_user %>
								<%= link_to "ユーザー情報を編集する", edit_user_path(@user), :class => "btn btn-primary" %>
							<% end %>
						<% else %>
							<p>
								ゲストログイン中のため、<br>
								ユーザー編集は行えません。
							</p>
						<% end %>
					</td>
			  </tr>
			  <tr>
			  	<td></span><%= link_to "お問い合わせする", new_contact_path, :class => "btn btn-primary" %></td>
			  	<td>
			  		<% if @user.name == "ゲストユーザー" %>
			  			<%= link_to "ログアウト", user_path(@user), method: :delete, :class => "btn btn-primary" %>
			  		<% else %>
			  			<%= link_to "ログアウト", destroy_user_session_path, method: :delete, :class => "btn btn-primary" %>
			  		<% end %>
			  	</td>
			  </tr>
			</table>
			<% end %>
		</div>
	</div>
</div>